### ISSUE TITLE
previous day data hours 21-24

### ISSUE THREAD

**Issue by gregfortress** [ropensci/riem#21]
I am running this package at 6am EST. I am trying to pull the weather data for the previous day, but I only get hours 1-20. I need all 24 hours. When can I grab hours 21-24?

Please advise. The latest I could possibly run it is 8:30am.

**Comment by maelle** [comment]
Hi @gregfortress! This is something we should ask to the awesome maintainer of the data source, @akrherz (thanks @akrherz!).
Maybe you should mention which station(s) and timezones are meant.

**Comment by akrherz** [comment]
I will figure this out today, yes having an example request would be good.

**Comment by gregfortress** [comment]
Right now, I think it's user error on my end. I think we're grabbing yesterday's data, in UTC. When that gets translated into America CST, it means I only have hours 1-20. I'll update you if this is not the case.

Thanks for your responses @maelle @akrherz

**Comment by akrherz** [comment]
@gregfortress On 6 Nov 2018, I [fixed a bug](https://github.com/akrherz/iem/commit/bdc1a25322951e4825e7622e1e75cc612d45ca4b#diff-b6029db4d7b83936de9703cb33020136) on my end that was not properly considering the start and end date provided by the user.  Perhaps this was previously working by mistake prior to my change.  Please let me know though how this turns out.  I code so many bugs and make so many silly mistakes :(

**Comment by akrherz** [comment]
@gregfortress is this issue now resolved?

**Comment by gregfortress** [comment]
Yep. As far as I can tell. Thanks.

**Comment by maelle** [comment]
Thanks @akrherz and happy data mining @gregfortress!
