### ISSUE TITLE
other data from IEM?

### ISSUE THREAD

**Issue by maelle** [ropensci/riem#4]
Once I'm finished with ASOS data (now I need to add unit tests, arument checks, etc.), I could add other sources of data, if there are other sources that give data for the whole world?

@akrherz are there other data sources on IEM for the whole world? Or maybe Iowa/US data you would recommend adding based on the current downloads? I'm really amazed by the IEM website. :smile: 

@sckott I'm tagging you as another judge of interest for R users.

**Comment by akrherz** [comment]
So this gets tricky and down in the weeds with regards to other data sources.  I am providing ASOS (general term denoting automated weather stations) data that is provided by NOAA over its satellite system in METAR format.  There is also data provided in SYNOP and now even BUFR format, that I currently do not process.  I suspect much of this data is the same, but maybe not :/

Otherwise, I am blissfully ignorant of any other worldwide data sources.  The other big player in north american and perhaps some places outside of there is these folks: http://madis.noaa.gov/ , I sort of process their data, but don't have any worth-mentioning downloads for it.

**Comment by maelle** [comment]
@akrherz thanks for your answer! Many NOAA data sources are included in a R package called rnoaa. I'll focus on the METAR for now then. It's really nice that your website allows to access them!
